language: python
python:
  - "2.7"
install:
  - pip install .
  - pip install -r requirements.txt
  - python setup.py -q install
script:
  - nosetests --with-cov
  - examples/PlatformIO/run.sh --wget
after_success:
  - codecov
